### ISSUE TITLE
MetFrag Web beta Issue

### ISSUE THREAD

**Issue by JoaquinWojciech** [ipb-halle/MetFrag#11]
Hi, no results shown for the processed candidates.

![screenshot_2018-09-20 metfrag issue](https://user-images.githubusercontent.com/43432161/45799021-a8780680-bcde-11e8-8ee6-230ed64dc91d.png)

Regards,
Joaquin

**Comment by schymane** [comment]
I can confirm that I do not see any results for the queries I have tried as well.

**Comment by JoaquinWojciech** [comment]
Thanks Emma, feedback submitted.

**Comment by sneumann** [comment]
We're looking into it. Yours, Steffen

**Comment by sneumann** [comment]
Fixed. That was a fallout of an earlier failure of the server. 
Mitigation measures have been conjured, but not yet implemented. 
Sorry for the inconvenience. Yours, Steffen

**Comment by JoaquinWojciech** [comment]
Thank you Steffen.

**Comment by JoaquinWojciech** [comment]
Hi, it's the same issue again on MetFrag Web beta.

Regards,
Joaquin

**Comment by schymane** [comment]
It seems to work fine for me at the moment, can you try again?

**Comment by JoaquinWojciech** [comment]
It's working fine for now. Thanks!

**Comment by david3231** [comment]
Hi, the website is not responding. May I know when will the current issue be fixed? 

Thanks,
David

**Comment by david3231** [comment]
Hi @korseby , thanks but its not responding again.

**Comment by korseby** [comment]
Hm. Seems like MetFrag is crashing because it is out of memory. Normally it should restart but it doesn't. I'll attach the log.

Can you try to reduce the number of candidates? 17000 compounds is probably too much for the computer where MetfRag is currently running on. (If that request was coming from you, of course. - We do not save any personal information.) We will merge MetFrag to our cluster sometime in February - which has much more memory.

```INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Got 17977 candidate(s)
checkDatabaseThread thread is dead
17977 compound(s)
init scores
checks before processing
start processing
ProcessCompoundsThreadRunner run
prepareDatabaseSettings
prepareCompoundFilterSettings
prepareCompoundScoreSettings
prepareFragmenterSettings
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 10 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 20 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 30 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 40 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 50 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 60 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 70 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 80 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 90 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 100 %
Exception in thread "Thread-30" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at javolution.util.internal.map.MapView$KeySet.<init>(MapView.java:157)
	at javolution.util.internal.map.MapView.keySet(MapView.java:273)
	at javolution.util.FastSet.<init>(FastSet.java:59)
	at javolution.util.FastSet.<init>(FastSet.java:51)
	at javolution.util.FastBitSet.<init>(FastBitSet.java:39)
	at de.ipbhalle.metfraglib.FastBitArray.<init>(FastBitArray.java:81)
	at de.ipbhalle.metfraglib.scoreinitialisation.AutomatedLossFingerprintAnnotationScoreInitialiser.addNonExplainedLosses(AutomatedLossFingerprintAnnotationScoreInitialiser.java:407)
	at de.ipbhalle.metfraglib.scoreinitialisation.AutomatedLossFingerprintAnnotationScoreInitialiser.postProcessScoreParameters(AutomatedLossFingerprintAnnotationScoreInitialiser.java:234)
	at de.ipbhalle.metfraglib.process.CombinedMetFragProcess.postProcessScoresGlobal(CombinedMetFragProcess.java:420)
	at de.ipbhalle.metfraglib.process.CombinedMetFragProcess.run(CombinedMetFragProcess.java:202)
	at de.ipbhalle.metfragweb.container.BeanSettingsContainer.startCandidateProcessing(BeanSettingsContainer.java:1754)
	at de.ipbhalle.metfragweb.helper.ProcessCompoundsThreadRunner.run(ProcessCompoundsThreadRunner.java:71)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "http-bio-8080-AsyncTimeout" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.ConcurrentLinkedQueue.iterator(ConcurrentLinkedQueue.java:669)
Exception in thread "http-bio-8080-exec-8" 	at org.apache.tomcat.util.net.JIoEndpoint$AsyncTimeout.run(JIoEndpoint.java:158)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-19" Exception in thread "http-bio-8080-exec-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-27" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Jan 15, 2019 4:44:20 AM org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor run
SEVERE: Unexpected death of background thread ContainerBackgroundProcessor[StandardEngine[Catalina]]
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception in thread "ContainerBackgroundProcessor[StandardEngine[Catalina]]" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-24" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-34" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-22" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-30" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-20" Exception in thread "http-bio-8080-exec-44"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-bio-8080-exec-20"
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-bio-8080-exec-42"
Exception in thread "http-bio-8080-exec-4"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-bio-8080-exec-4"
Exception in thread "http-bio-8080-exec-26" Exception in thread "http-bio-8080-exec-46" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-49" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-43" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-29" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-Acceptor-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-47" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-32" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-8080-exec-21" java.lang.OutOfMemoryError: GC overhead limit exceeded
Jan 15, 2019 4:55:09 AM com.sun.faces.application.ApplicationImpl newThing
SEVERE: Unable to load class:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Jan 15, 2019 4:55:33 AM com.sun.faces.application.ApplicationImpl createComponentApplyAnnotations
SEVERE: JSF1068: Cannot instantiate component with component-type javax.faces.HtmlPanelGrid```

**Comment by david3231** [comment]
Hi @korseby ,  thanks for the information but that wasn't from me. I was just about to log on the website.

Ok great, I'm looking forward to it. Thank you very much.

**Comment by JoaquinWojciech** [comment]
@korseby 
Hi, the webpage is down. I'm planning to use MetFragR. I wonder if MetFrag Web & R share the same server?
Regards.

**Comment by schymane** [comment]
MetFragR should be independent of the web server …

**Comment by korseby** [comment]
It should be running again.

**Comment by david3231** [comment]
![image](https://user-images.githubusercontent.com/46667320/53858637-f9be4d00-4015-11e9-96e6-a74523b26a68.png)

@korseby Hi, the metfrag web is showing "Error fetching candidates".

**Comment by korseby** [comment]
Hi David,

I can see that MetFragBeta does not retrieve candidates.

Can you use the stable version (The Beta just went to stable last month)? I just tested it and it should work as expected.

https://msbi.ipb-halle.de/MetFrag/

Best wishes

**Comment by david3231** [comment]
Hi Korseby,

ok noted. thank you so much!

**Comment by sneumann** [comment]
Database on MetFragBeta has also been restarted. Yours, Steffen

**Comment by JoaquinWojciech** [comment]
@korseby
Hi, we're encountering database candidates fetching error in MetFrag Web.
Regards.

**Comment by JoaquinWojciech** [comment]
@korseby 
Hi, we're encountering database candidates fetching error in MetFrag Web.
Regards.

**Comment by korseby** [comment]
Hi @JoaquinWojciech ,

we know. Our worker nodes rebooted and we are working on the issue. As this is not related to MetFrag development, can you send a mail to denbi-mash ÄT ipb-halle.de in the future? This way, you can reach us (Rene, Steffen, Hendrik and me) directly.

Best wishes

**Comment by JoaquinWojciech** [comment]
Noted and thank you @korseby.
